# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_amd64_v3
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - linux_mips_softfloat
      - linux_mips_hardfloat
      - linux_mipsle_softfloat
      - linux_mipsle_hardfloat
      - linux_mips64
      - linux_mips64le
      - freebsd_amd64
      - windows_386
      - windows_amd64
      - windows_amd64_v3
      - windows_arm64
    flags:
      - -trimpath
    ldflags: |
      -s -w
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

upx:
  - # Whether to enable it or not.
    #
    # Templates: allowed.
    enabled: true

    # # Filter by GOOS.
    # goos: [linux, darwin]

    # # Filter by GOARCH.
    # goarch: [arm, amd64]

    # # Filter by GOARM.
    # goarm: [8]

    # # Filter by GOAMD64.
    # goamd64: [v1]

    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: 9

    # Whether to try LZMA (slower).
    lzma: true

    # Whether to try all methods and filters (slow).
    #brute: true

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
